### PR TITLE
12-Shubham-DevLake-on-AWS-ec2.md

### PR DESCRIPTION
**Pull request by shubham-cmyk**
Title - [Technical Blog] - Launching Apache DevLake (Incubating) on an AWS instance

Quick Pointers - 
1. Launching an AWS instance
2. Setting up an SSH connection for both Linux and Windows User
3. Installing DevLake on the ec2- Instance
4. Configure the Inbound Rule of AWS
5. Final Changes on IP and Launch the containers.

URL -  docs : https://docs.google.com/document/d/1GdU9Y7PS7ixm7ubZOHQDv4ZPwCWtXs67NiRrDinofek/edit?usp=sharing
Medium : https://shubham-2001.medium.com/launching-apache-devlake-incubating-on-an-aws-instance-1a9ada1ecc86

Reference Issue #1

### CODE REVIEW

**Comment by ghost** [comment]
Hey @shubham-cmyk, could you rename the file to "12-Shubham-DevLake-on-AWS-ec2.md"?

If you have published this on Google Docs or Medium, you can share the link of the draft in the same.md file (need not copy & paste the entire thing)"

Follow this format if it helps for `12-Shubham-DevLake-on-AWS-ec2.md`
Title:
Pointers:
URL:

**Comment by ghost** [comment]
https://shubham-2001.medium.com/launching-apache-devlake-incubating-on-an-aws-instance-1a9ada1ecc86

@shubham-cmyk add hyperlinks to wherever Apache Devlake is mentioned

**Comment by shubham-cmyk** [comment]
@JoshuaPoddoku  Hyperlink directing to devlake github repo or our apache devlake website ? 
I could edit in Medium and google doc. which I have submitted.

**Comment by ghost** [comment]
DevLake website should be good!

**Pull request merged**
